--- Makefile.orig	2009-07-05 12:23:30.000000000 -0700
+++ Makefile	2009-07-05 12:23:43.000000000 -0700
@@ -200,7 +200,7 @@
 sharedstatedir = ${prefix}/com
 sysconfdir = /opt/darkmatter/etc
 target_alias = 
-SUBDIRS = src example tests docs
+SUBDIRS = src tests docs
 include_HEADERS = \
 	include/libssh2.h		\
 	include/libssh2_publickey.h	\
