include ../mklib/build.mk

pkg_name := libtool
pkg_version := 2.4
pkg_release := 1

CONFIG_OPTS := --prefix=$(BUILD_ROOT)$(PREFIX_DIR) --with-gnu-ld  --enable-ltdl-install
BUILD_ROOT_ONLY := 1
REMOVE_PATHS += $(INCLUDE_DIR)/*ltdl* $(LIB_DIR)/libltdl* 

include ../mklib/pkggnu.mk
include ../mklib/packages.mk
