Document: darkmatter-stack
Title: Debian darkmatter-stack Manual
Author: <insert document author here>
Abstract: This manual describes what darkmatter-stack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/darkmatter-stack/darkmatter-stack.sgml.gz

Format: postscript
Files: /usr/share/doc/darkmatter-stack/darkmatter-stack.ps.gz

Format: text
Files: /usr/share/doc/darkmatter-stack/darkmatter-stack.text.gz

Format: HTML
Index: /usr/share/doc/darkmatter-stack/html/index.html
Files: /usr/share/doc/darkmatter-stack/html/*.html
