Document: darkmatter-depends
Title: Debian darkmatter-depends Manual
Author: <insert document author here>
Abstract: This manual describes what darkmatter-depends is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/darkmatter-depends/darkmatter-depends.sgml.gz

Format: postscript
Files: /usr/share/doc/darkmatter-depends/darkmatter-depends.ps.gz

Format: text
Files: /usr/share/doc/darkmatter-depends/darkmatter-depends.text.gz

Format: HTML
Index: /usr/share/doc/darkmatter-depends/html/index.html
Files: /usr/share/doc/darkmatter-depends/html/*.html
