include ../mklib/build.mk

# CVS checkout on 20110730

pkg_name := libeio
pkg_version := 1.0
pkg_release := 1

REMOVE_PATHS = $(LIB_DIR)/libeio* $(INCLUDE_DIR)/eio.h

include ../mklib/pkggnu.mk
include ../mklib/packages.mk
